# Generated by Django 5.2.7 on 2025-10-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_transitagency_supported_card_schemes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopyEligibility",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("language", models.CharField(choices=[("en", "English"), ("es", "Spanish")], max_length=2)),
                ("headline", models.CharField(max_length=255)),
                ("form_text", models.CharField(max_length=255)),
                ("id_agency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.transitagency")),
            ],
        ),
    ]
